### ISSUE TITLE
Installation error on flash plugin

### ISSUE THREAD

**Issue by wiczerd** [tiliado/tiliado-repositories#12] opened 2016-10-20 19:15 UTC
- ['/usr/bin/tiliado-repositories', '-d', 'ubuntu', '-r', 'xenial', '-v', 'stable', '-p', 'nuvolaplayer', '-i', 'nuvolaplayer3', '--server', 'tiliado.eu', '--protocol', 'https' ]
- ['apt-get', 'remove', '-y', 'nuvolaplayer3*']
  Reading package lists...
  Building dependency tree...
  Reading state information...
  Package 'nuvolaplayer' is not installed, so not removed
  The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-36 linux-headers-4.4.0-36-generic linux-headers-4.4.0-38
  linux-headers-4.4.0-38-generic linux-image-4.4.0-36-generic
  linux-image-4.4.0-38-generic linux-image-extra-4.4.0-36-generic
  linux-image-extra-4.4.0-38-generic linux-signed-image-4.4.0-36-generic
  linux-signed-image-4.4.0-38-generic
  Use 'apt autoremove' to remove them.
  0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
- ['apt-key', 'adv', '--keyserver', 'hkp://keyserver.ubuntu.com:80', '--recv-keys', '40554B8FA5FE6F6A']
  Executing: /tmp/tmp.nckURoo2wd/gpg.1.sh --keyserver
  hkp://keyserver.ubuntu.com:80
  --recv-keys
  40554B8FA5FE6F6A
  gpg: requesting key A5FE6F6A from hkp server keyserver.ubuntu.com
  gpg: key A5FE6F6A: public key "Ji\xc5\x99\udced Janou\xc5\xa1ek janousek.jiri@gmail.com" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
- [disable repos: tiliado.eu => nuvolaplayer]
- [makedirs '/etc/apt/sources.list.d']
- [write '/etc/apt/sources.list.d/tiliado-nuvolaplayer.list']
  deb https://wiczerd:845926ad4d83f988f05d906d30353977f3bb6b53@tiliado.eu/nuvolaplayer/repository/deb/ xenial stable # nuvolaplayer (stable)
- ['apt-get', 'update']
  Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
  Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
  Hit:4 http://dl.google.com/linux/chrome/deb stable Release
  Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
  Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
  Hit:7 http://archive.canonical.com/ubuntu xenial InRelease
  Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease
  Get:10 https://tiliado.eu/nuvolaplayer/repository/deb xenial InRelease [15.2 kB]
  Hit:11 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
  Get:12 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 Packages [4288 B]
  Get:13 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable i386 Packages [4292 B]
  Fetched 23.8 kB in 1s (19.3 kB/s)
  Reading package lists...
- ['apt-get', 'install', '-y', 'nuvolaplayer3']
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-36 linux-headers-4.4.0-36-generic linux-headers-4.4.0-38
  linux-headers-4.4.0-38-generic linux-image-4.4.0-36-generic
  linux-image-4.4.0-38-generic linux-image-extra-4.4.0-36-generic
  linux-image-extra-4.4.0-38-generic linux-signed-image-4.4.0-36-generic
  linux-signed-image-4.4.0-38-generic
  Use 'apt autoremove' to remove them.
  The following additional packages will be installed:
  adobe-flash-properties-gtk adobe-flashplugin libdiorite0.2
  nuvolaplayer3-8tracks nuvolaplayer3-all-services
  nuvolaplayer3-amazon-cloud-player nuvolaplayer3-bandcamp
  nuvolaplayer3-deezer nuvolaplayer3-google-play-music nuvolaplayer3-groove
  nuvolaplayer3-jango nuvolaplayer3-kexp nuvolaplayer3-logitech-media-server
  nuvolaplayer3-mixcloud nuvolaplayer3-plex nuvolaplayer3-siriusxm
  nuvolaplayer3-soundcloud nuvolaplayer3-spotify nuvolaplayer3-tunein
  nuvolaplayer3-yandex-music nuvolaplayer3-youtube
  Suggested packages:
  x-ttcidfont-conf msttcorefonts ttf-bitstream-vera | ttf-dejavu
  ttf-xfree86-nonfree xfs libnspr4-0d
  The following NEW packages will be installed:
  adobe-flash-properties-gtk adobe-flashplugin libdiorite0.2 nuvolaplayer3
  nuvolaplayer3-8tracks nuvolaplayer3-all-services
  nuvolaplayer3-amazon-cloud-player nuvolaplayer3-bandcamp
  nuvolaplayer3-deezer nuvolaplayer3-google-play-music nuvolaplayer3-groove
  nuvolaplayer3-jango nuvolaplayer3-kexp nuvolaplayer3-logitech-media-server
  nuvolaplayer3-mixcloud nuvolaplayer3-plex nuvolaplayer3-siriusxm
  nuvolaplayer3-soundcloud nuvolaplayer3-spotify nuvolaplayer3-tunein
  nuvolaplayer3-yandex-music nuvolaplayer3-youtube
  0 upgraded, 22 newly installed, 0 to remove and 3 not upgraded.
  Need to get 11.6 MB of archives.
  After this operation, 41.6 MB of additional disk space will be used.
  Get:1 http://archive.canonical.com/ubuntu xenial/partner amd64 adobe-flashplugin amd64 1:20161011.1-0ubuntu0.16.04.1 [10.3 MB]
  Get:2 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 libdiorite0.2 amd64 0.2.1-0+1~xenial [142 kB]
  Get:3 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-8tracks amd64 5.1-1~xenial [35.0 kB]
  Get:4 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-amazon-cloud-player amd64 5.1-1~xenial [11.0 kB]
  Get:5 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-bandcamp amd64 2.1-1~xenial [28.9 kB]
  Get:6 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-deezer amd64 2.4-1~xenial [25.4 kB]
  Get:7 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-google-play-music amd64 5.17-1~xenial [33.1 kB]
  Get:8 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-groove amd64 1.2-1~xenial [55.4 kB]
  Get:9 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-jango amd64 2.2-1~xenial [49.9 kB]
  Get:10 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-kexp amd64 1.0-1~xenial [9222 B]
  Get:11 http://archive.canonical.com/ubuntu xenial/partner amd64 adobe-flash-properties-gtk amd64 1:20161011.1-0ubuntu0.16.04.1 [114 kB]
  Get:12 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-logitech-media-server amd64 2.0-1~xenial [17.6 kB]
  Get:13 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-mixcloud amd64 3.1-1~xenial [36.2 kB]
  Get:14 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-plex amd64 1.2-1~xenial [35.7 kB]
  Get:15 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-siriusxm amd64 1.2-1~xenial [77.9 kB]
  Get:16 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-soundcloud amd64 1.2-1~xenial [81.0 kB]
  Get:17 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-spotify amd64 2.2-1~xenial [37.9 kB]
  Get:18 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-tunein amd64 1.0-1~xenial [17.7 kB]
  Get:19 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-yandex-music amd64 1.3-1~xenial [31.3 kB]
  Get:20 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-youtube amd64 1.2-1~xenial [78.7 kB]
  Get:21 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3-all-services amd64 0.201609281045-1~xenial [1058 B]
  Get:22 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 nuvolaplayer3 amd64 3.0.4-0+1~xenial [370 kB]
  debconf: unable to initialize frontend: Dialog
  debconf: (TERM is not set, so the dialog frontend is not usable.)
  debconf: falling back to frontend: Readline
  debconf: unable to initialize frontend: Readline
  debconf: (This frontend requires a controlling tty.)
  debconf: falling back to frontend: Teletype
  dpkg-preconfigure: unable to re-open stdin: 
  Fetched 11.6 MB in 9s (1176 kB/s)
  Selecting previously unselected package adobe-flashplugin.
  (Reading database ... 
  (Reading database ... 5%
  (Reading database ... 10%
  (Reading database ... 15%
  (Reading database ... 20%
  (Reading database ... 25%
  (Reading database ... 30%
  (Reading database ... 35%
  (Reading database ... 40%
  (Reading database ... 45%
  (Reading database ... 50%
  (Reading database ... 55%
  (Reading database ... 60%
  (Reading database ... 65%
  (Reading database ... 70%
  (Reading database ... 75%
  (Reading database ... 80%
  (Reading database ... 85%
  (Reading database ... 90%
  (Reading database ... 95%
  (Reading database ... 100%
  (Reading database ... 445678 files and directories currently installed.)
  Preparing to unpack .../adobe-flashplugin_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb ...
  Unpacking adobe-flashplugin (1:20161011.1-0ubuntu0.16.04.1) ...
  dpkg: error processing archive /var/cache/apt/archives/adobe-flashplugin_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb (--unpack):
  trying to overwrite '/usr/share/icons/hicolor/16x16/apps/flash-player-properties.png', which is also in package adobe-flash-player 2014-12.09.0-0ubuntu0.14.04.1
  dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
  Selecting previously unselected package adobe-flash-properties-gtk.
  Preparing to unpack .../adobe-flash-properties-gtk_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb ...
  Unpacking adobe-flash-properties-gtk (1:20161011.1-0ubuntu0.16.04.1) ...
  dpkg: error processing archive /var/cache/apt/archives/adobe-flash-properties-gtk_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb (--unpack):
  trying to overwrite '/usr/bin/flash-player-properties', which is also in package adobe-flash-player 2014-12.09.0-0ubuntu0.14.04.1
  dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
  Selecting previously unselected package libdiorite0.2.
  Preparing to unpack .../libdiorite0.2_0.2.1-0+1~xenial_amd64.deb ...
  Unpacking libdiorite0.2 (0.2.1-0+1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-8tracks.
  Preparing to unpack .../nuvolaplayer3-8tracks_5.1-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-8tracks (5.1-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-amazon-cloud-player.
  Preparing to unpack .../nuvolaplayer3-amazon-cloud-player_5.1-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-amazon-cloud-player (5.1-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-bandcamp.
  Preparing to unpack .../nuvolaplayer3-bandcamp_2.1-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-bandcamp (2.1-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-deezer.
  Preparing to unpack .../nuvolaplayer3-deezer_2.4-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-deezer (2.4-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-google-play-music.
  Preparing to unpack .../nuvolaplayer3-google-play-music_5.17-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-google-play-music (5.17-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-groove.
  Preparing to unpack .../nuvolaplayer3-groove_1.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-groove (1.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-jango.
  Preparing to unpack .../nuvolaplayer3-jango_2.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-jango (2.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-kexp.
  Preparing to unpack .../nuvolaplayer3-kexp_1.0-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-kexp (1.0-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-logitech-media-server.
  Preparing to unpack .../nuvolaplayer3-logitech-media-server_2.0-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-logitech-media-server (2.0-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-mixcloud.
  Preparing to unpack .../nuvolaplayer3-mixcloud_3.1-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-mixcloud (3.1-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-plex.
  Preparing to unpack .../nuvolaplayer3-plex_1.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-plex (1.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-siriusxm.
  Preparing to unpack .../nuvolaplayer3-siriusxm_1.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-siriusxm (1.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-soundcloud.
  Preparing to unpack .../nuvolaplayer3-soundcloud_1.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-soundcloud (1.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-spotify.
  Preparing to unpack .../nuvolaplayer3-spotify_2.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-spotify (2.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-tunein.
  Preparing to unpack .../nuvolaplayer3-tunein_1.0-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-tunein (1.0-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-yandex-music.
  Preparing to unpack .../nuvolaplayer3-yandex-music_1.3-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-yandex-music (1.3-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-youtube.
  Preparing to unpack .../nuvolaplayer3-youtube_1.2-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-youtube (1.2-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3-all-services.
  Preparing to unpack .../nuvolaplayer3-all-services_0.201609281045-1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3-all-services (0.201609281045-1~xenial) ...
  Selecting previously unselected package nuvolaplayer3.
  Preparing to unpack .../nuvolaplayer3_3.0.4-0+1~xenial_amd64.deb ...
  Unpacking nuvolaplayer3 (3.0.4-0+1~xenial) ...
  Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
  Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
  Rebuilding /usr/share/applications/bamf-2.index...
  Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
  Processing triggers for mime-support (3.59ubuntu1) ...
  Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
  Errors were encountered while processing:
  /var/cache/apt/archives/adobe-flashplugin_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb
  /var/cache/apt/archives/adobe-flash-properties-gtk_1%3a20161011.1-0ubuntu0.16.04.1_amd64.deb
  E: Sub-process /usr/bin/dpkg returned an error code (1)
  Subprocess Error: Command '['apt-get', 'install', '-y', 'nuvolaplayer3']' returned non-zero exit status 100
- [Return code = 4]

**Comment by wiczerd** [comment] 2016-10-20 19:32
Update on this: looks like the problem is that my system is not installing the Flash Plugin well, so I think I need to work that out first.

**Comment by jiri-janousek** [comment] 2016-10-20 19:41
Hello @wiczerd. Could you try to uninstall the adobe-flash-player package first?

**Comment by wiczerd** [comment] 2016-10-20 21:47
Ah man. I am trying. I'm in an unmet dependency loop. Well, that blew my APT

**Comment by wiczerd** [comment] 2016-10-21 15:43
I removed Flash Plugin (dpkg ---purge), but I can't remove nuvolaplayer3 because it pops up all of the sub programs (e.g. nuvolaplayer3-spotify) trying to remove one of these gives me the same unmet dependencies. 
After this, I ran apt-get install -f, which then re-install Flash and completed the install of the rest of Nuvola. Seemed to work

**Comment by jiri-janousek** [comment] 2016-10-21 20:46
> I used your installer to set up the repository and it worked really poorly.

Actually, the installer worked excellently. The problem is elsewhere: The adobe-flashplugin and adobe-flash-player packages do conflict but are not marked as conflicting. It's just fascinating that apt found it out eventually but didn't do anything about it.

Anyway, glad to hear you have solved the issue. Btw, where did you get the adobe-flash-player? I can't find it in Ubuntu repos.

**Closed as completed** 2016-10-22 11:08 UTC

**Comment by jiri-janousek** [comment] 2016-10-25 18:42
> I used your installer to set up the repository and it worked really
> poorly.

Actually, the installer worked excellently. The problem is elsewhere: The
adobe-flashplugin and adobe-flash-player packages do conflict but are not
marked as conflicting. It's just fascinating that apt found out it
eventually but didn't do anything about it.

Anyway, let's try to fix the disaster. Does `sudo apt-get install -f` help?
If not, could you post the whole output?

**Comment by wiczerd** [comment] 2016-10-26 19:04
Thanks a lot for the help, and the program has been working lovely. 
This guy: adobe-flashplugin was both the cause and solution to all the problems (Homer, beer reference there). I purged it and then re-installed. It was actually in my repository though: maybe I've got the non-free repos available in Ubuntu 16.04?
